name: Continuous Integration
on: 
  pull_request:  #event
      branches:[develop2]
  push:
       branches:[develop2]
env:
    DATABASE_URL="postgresql://postgres:admin123@localhost:5432/mydb?schema=public"

jobs:
  testing_api: #name of job
      runs-on:ubuntu-latest #system api will run on
  services:
    postgres:
      image:postgres:14-alpine
       env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin123
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Clone repo code into the runner
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Run the Unit/Integration test
        run: npm test