name: Continuous Integration
on: 
  pull_request:  #event
      branches:[develop2]
  push:
       branches:[develop2]


jobs:
  testing_api: #name of job
      runs-on:ubuntu-latest #system api will run on
      
  steps:
    - name:clone repo code into the runner
      uses:actions/checkout@v2 #its an action on github actions used to copy code from your repo
    - name: Setup Node.js
        uses:actions/setup-node@v1
      with:
          node-version:20

    - name:Install Dependencies
      run:npm ci

    - name:Run the Unit/Intergartion test
        run:npm test